# Generated by Django 4.2.7 on 2023-12-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
            ],
        ),
    ]
